### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by lamby** [WayneD/text-aid#1]
Love the extension. This does not apper to be the version that's on the Chrome Extension store however; the `manifest_version` is missing and it also appears to use inline scripts and stuff that Chrome appears to reject...

(Asking as I would love to send a PR to fix a Fastmail-specific issue.)

**Comment by WayneD** [comment]
I apparently forgot I put this on git hub under this name, and put a newer version up just recently: https://github.com/WayneD/TextEditAid
